import "./globals.css";
import Header from "./(header)/header";
import { Nunito } from "next/font/google";

const nunito = Nunito({
	subsets: ["latin"],
	variable: "--font-nunito",
});
export const metadata = {
	title: "Coast Guard App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${nunito.variable} font-nunito`}>
				<section>
					<Header />
					{children}
				</section>
			</body>
		</html>
	);
}
