import "./globals.css";
import Header from "./header";


export const metadata = {
  title: "Coast Guard App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section>
          <Header />
          {children}
        </section>
      </body>
    </html>
  );
}
